# Generated by Django 5.2.4 on 2026-06-24 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('initial_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capsule_url', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('metacritic_score', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_korean', models.BooleanField(default=False)),
                ('required_age', models.IntegerField(default=0)),
                ('offline', models.BooleanField(default=False)),
                ('playtime', models.IntegerField(blank=True, null=True)),
                ('is_singleplayer', models.BooleanField(blank=True, default=None, null=True)),
                ('is_multiplayer', models.BooleanField(blank=True, default=None, null=True)),
                ('is_coop', models.BooleanField(blank=True, default=None, null=True)),
                ('rawg_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('steam_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'game',
                'ordering': ['-game_id'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('mood_id', models.AutoField(primary_key=True, serialize=False)),
                ('mood_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'mood',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'platform',
            },
        ),
        migrations.CreateModel(
            name='GameVideo',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('video_url', models.CharField(max_length=255)),
                ('thumbnail', models.CharField(blank=True, max_length=255)),
                ('channel', models.CharField(blank=True, default='', max_length=100)),
                ('published_at', models.CharField(blank=True, default='', max_length=10)),
                ('video_type', models.CharField(choices=[('trailer', '트레일러'), ('walkthrough', '공략')], default='trailer', max_length=20)),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='games.game')),
            ],
            options={
                'db_table': 'game_video',
            },
        ),
        migrations.CreateModel(
            name='GameTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='games.genre')),
            ],
            options={
                'db_table': 'game_tag',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='games', through='games.GameTag', to='games.genre'),
        ),
        migrations.CreateModel(
            name='GameMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('mood', models.ForeignKey(db_column='mood_id', on_delete=django.db.models.deletion.CASCADE, to='games.mood')),
            ],
            options={
                'db_table': 'game_mood',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='moods',
            field=models.ManyToManyField(blank=True, related_name='games', through='games.GameMood', to='games.mood'),
        ),
        migrations.CreateModel(
            name='GamePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('platform', models.ForeignKey(db_column='platform_id', on_delete=django.db.models.deletion.CASCADE, to='games.platform')),
            ],
            options={
                'db_table': 'game_platform',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='games', through='games.GamePlatform', to='games.platform'),
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('screenshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=255)),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='games.game')),
            ],
            options={
                'db_table': 'screenshot',
            },
        ),
        migrations.AddConstraint(
            model_name='gametag',
            constraint=models.UniqueConstraint(fields=('game', 'tag'), name='unique_game_tag'),
        ),
        migrations.AddConstraint(
            model_name='gamemood',
            constraint=models.UniqueConstraint(fields=('game', 'mood'), name='unique_game_mood'),
        ),
        migrations.AddConstraint(
            model_name='gameplatform',
            constraint=models.UniqueConstraint(fields=('game', 'platform'), name='unique_game_platform'),
        ),
    ]
