# Generated by Django 5.2.4 on 2026-06-23 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('initial_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capsule_url', models.CharField(blank=True, max_length=255)),
                ('metacritic_score', models.IntegerField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_korean', models.BooleanField(default=False)),
                ('required_age', models.IntegerField(default=0)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('offline', models.BooleanField(default=False)),
                ('rawg_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('steam_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'game',
                'ordering': ['-game_id'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='GameVideo',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('video_url', models.CharField(max_length=255)),
                ('thumbnail', models.CharField(blank=True, max_length=255)),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='games.game')),
            ],
            options={
                'db_table': 'game_video',
            },
        ),
        migrations.CreateModel(
            name='GameTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='games.genre')),
            ],
            options={
                'db_table': 'game_tag',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='games', through='games.GameTag', to='games.genre'),
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('screenshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=255)),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='games.game')),
            ],
            options={
                'db_table': 'screenshot',
            },
        ),
        migrations.AddConstraint(
            model_name='gametag',
            constraint=models.UniqueConstraint(fields=('game', 'tag'), name='unique_game_tag'),
        ),
    ]
