# Generated by Django 5.2.4 on 2026-06-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamevideo',
            name='channel',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='gamevideo',
            name='published_at',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
