# Generated by Django 5.2.4 on 2026-06-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamevideo_channel_gamevideo_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamevideo',
            name='video_type',
            field=models.CharField(choices=[('trailer', '트레일러'), ('walkthrough', '공략')], default='trailer', max_length=20),
        ),
    ]
