# Generated by Django 5.2.4 on 2026-06-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_searchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='thumbnail_subjects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
