# Generated by Django 5.2.4 on 2026-06-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_thumbnail_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price_updated_at',
            field=models.DateTimeField(blank=True, db_column='price_updated_at', help_text='가격을 마지막으로 갱신한 시각. null=아직 한 번도 갱신 안 됨(최우선 대상).', null=True),
        ),
    ]
