# Generated by Django 5.2.4 on 2026-06-24 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gamevideo_video_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('mood_id', models.AutoField(primary_key=True, serialize=False)),
                ('mood_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'mood',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='is_coop',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_multiplayer',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_singleplayer',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='playtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GameMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('mood', models.ForeignKey(db_column='mood_id', on_delete=django.db.models.deletion.CASCADE, to='games.mood')),
            ],
            options={
                'db_table': 'game_mood',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='moods',
            field=models.ManyToManyField(blank=True, related_name='games', through='games.GameMood', to='games.mood'),
        ),
        migrations.AddConstraint(
            model_name='gamemood',
            constraint=models.UniqueConstraint(fields=('game', 'mood'), name='unique_game_mood'),
        ),
    ]
