# Generated by Django 5.2.4 on 2026-06-24 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('prompt_input', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation_log',
                'ordering': ['-log_id'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True)),
                ('match_score', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_results', to='games.game')),
                ('log', models.ForeignKey(db_column='log_id', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='recommendations.recommendationlog')),
            ],
            options={
                'db_table': 'recommendation_result',
                'ordering': ['-match_score'],
            },
        ),
    ]
